dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: qXYLJTR7IVkA+Y/OqQxIkt19XDTo7tkVVfO4q1vpcrYePgNraWkFnEgYN6GlEBjofEXpGDZEHP+Lc4Lxwk/aaVpGwqyCDv+Tg8QeVw1VXI4HUz6v4GSKt5HQAPwdMR9TmBk6TwyDYPG8UWjCTglLQTkL0SkuioRnZWYF8x3CLH4YBLy531nkWCWPqjUy2baIYaVQrcx9exBCj8JHq/NO7mk0QfKpbW0vbzYvHAdCa9skVI9mo9yHAttrigD6UcdPcJRgpBOREpYTTcqo/UMPeuhRTYKM40+OwTn2ZJ0oc3w0Omuo+VN4S5biX7Pw+zRv+tAyjOWqsXrxXnYKDvOomOypp+avFBdmwv+pKNiQrNac/1wYkL9sjRxIPVHbYVLmpiUTuuRhP3COMyWAV0lzFgND88/FYnK1Dn04X0fXS2TztQwMacTVbsEiG9gwN/HQ1AleIMmbV04F+/k9ibsT5utYB9EfdeyELSyuIGdfLXeHlCbRSfiq4l82Q/DVrtjmSLcwzvsSJlvPdpzeIsNlBSm8Q64BmhwwnMrT3ibyJkhqqZUFJM6DaDyDJFxx7tFp3HEth3+jPfJKWr6JCp2ng8GQUFXKx3vaWgnYXo0P8zRTs/13XWV/BeeagRH9cqEmpRKktPzkVt0T0lvc5SqLJtuWKO9IPkNtzLBstCOPFWI=
