dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-02/run.sh |
  bash
notifications:
  slack:
    secure: l6Hg6sMJBm6waURHA2M8TpK8ORAaqR+c7daJ1dCWCrhTlUKCPLpxOd0Zh03IqeTMe6AD8ktEDapMfCgxJ8HLNfal980vg4wFLbKKPRrw3Pu03FhEpoFuG+Cu1UibUD7bEqy5+3tZan7zLwocnFmOL322cEnPNXBxQrs5Z+I8GpVfBPmVKWSe0xgbvq52lPbpOL51OqKV7UxcudyNqoNB1E/3+ys/tVv8rZ9eJJtTaq5KvXwalgycCRj/S0+7V/ZMJYVFN5TWWjtH6CGe+ILDcpYzUsvQiNj1frazUFumMUnmmJaW5IqTcTZX4KMWlOnNT9M8vG3OADBR0jX9YGtOxZfDsg8gUq2HjnQAf4Ev6XTeywUfGKfl0Yja18vVQyevXxW/U1uwz1fxRiiQPZIrywJoffMxrbNqnVQNFFZSTUQIGFIE7pMhGFhA4kxnrG/9AwjqO13D6nd4NGZ+d3fRPDf4N+bHgqPYEEyALOdqD2G/+dqbv7LyJLFFiOzw3OfzrKJvEPGLjikEq8DkkC9XLEkugj2sxFahHMjuvctQhm20+mFWxI23xYo8fLxGRu9gsDID+PEtBsKf2bCRqhygvBzCkAcO6HT9ZpUR1eTlwsxWBYIzOwmb/kLzVJJDfMJVVga8GMrjTuGuXF0Qtidf1sdK5QLJupyhv1B3HeQLGwY=
