---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "comment.fullname" . }}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
    - secretName: ui-ingress
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "comment.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
