kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 4XYkiXThSLcgL+WeX1v4oucpHwtdz+pV+1fU10+s0aQ=
      - identity: {}
